# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_zero_shot_linkedin_test.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_zero_shot_linkedin_test.ipynb 13
df.input = df.input.astype(str)
df.input = df.input.str.replace('\\n',' ',regex=False)
